# Generated by Django 4.2.5 on 2024-05-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='memberNum',
            new_name='memberId',
        ),
    ]
