# Generated by Django 4.1 on 2024-05-10 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderDate", models.DateTimeField(auto_now_add=True)),
                ("totPrice", models.CharField(max_length=10)),
                (
                    "send",
                    models.CharField(
                        choices=[
                            ("7-11pick", "7-11取貨"),
                            ("homepick", "店到家宅配"),
                            ("familypick", "全家取貨"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pay",
                    models.CharField(
                        choices=[("7-11pick", "現金"), ("homepick", "信用卡")], max_length=10
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="inventorychange",
            name="change_type",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default="商品顏色", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventorychange",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totQua", models.CharField(max_length=10)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.order"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "score",
                    models.CharField(
                        choices=[
                            ("onestar", "★"),
                            ("twostar", "★★"),
                            ("threestar", "★★★"),
                            ("fourstar", "★★★★"),
                            ("fivestar", "★★★★★"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scoreDate", models.DateTimeField(auto_now_add=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.order"
                    ),
                ),
            ],
        ),
    ]
