# Generated by Django 4.1 on 2024-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_order_remove_inventorychange_change_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorychange",
            name="change_type",
            field=models.CharField(
                choices=[("increase", "增加"), ("decrease", "減少"), ("adjustment", "調整")],
                default="increase",
                max_length=20,
            ),
        ),
    ]
