# Generated by Django 4.1 on 2024-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_product_inventorychange"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorychange",
            name="color",
            field=models.CharField(default="未指定", max_length=20),
        ),
        migrations.AddField(
            model_name="inventorychange",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventorychange",
            name="size",
            field=models.CharField(default="N/A", max_length=20),
        ),
        migrations.AlterField(
            model_name="inventorychange",
            name="change_type",
            field=models.CharField(
                choices=[("increase", "增加"), ("decrease", "减少"), ("adjustment", "调整")],
                max_length=20,
            ),
        ),
    ]
