# Generated by Django 4.1 on 2024-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_inventorychange_color_inventorychange_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorychange",
            name="color",
            field=models.CharField(default="商品顏色", max_length=20),
        ),
        migrations.AlterField(
            model_name="inventorychange",
            name="size",
            field=models.CharField(default="商品尺寸", max_length=20),
        ),
    ]
