# Generated by Django 4.1 on 2024-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.RemoveField(
            model_name="member",
            name="id",
        ),
        migrations.AlterField(
            model_name="member",
            name="memberId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
