# Generated by Django 4.1 on 2024-05-10 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_inventorychange_change_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorychange",
            old_name="product",
            new_name="product_id",
        ),
    ]
