# Generated by Django 4.1 on 2024-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_alter_inventorychange_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorychange",
            name="price",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
