# Generated by Django 4.2.5 on 2024-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_rename_product_inventorychange_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='borndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
