# Generated by Django 4.2.5 on 2024-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_member_borndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
