# Generated by Django 4.1 on 2024-05-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0005_alter_inventorychange_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="shoppingCart",
            fields=[
                ("shopNum", models.AutoField(primary_key=True, serialize=False)),
                ("orderQua", models.CharField(default=0, max_length=10)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.product"
                    ),
                ),
            ],
        ),
    ]
