# Generated by Django 4.2.5 on 2024-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_member_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='borndate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
