# Generated by Django 4.2.5 on 2024-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_member_borndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='man', max_length=10),
        ),
    ]
