# Generated by Django 4.2.5 on 2024-06-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_comment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='order_id',
        ),
    ]
