# Generated by Django 4.2.5 on 2024-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.CharField(choices=[('1分', '★'), ('2分', '★★'), ('3分', '★★★'), ('4分', '★★★★'), ('5分', '★★★★★')], max_length=10),
        ),
    ]
